---
os: osx
language: node_js
node_js: 12
cache:
  yarn: true
  cocoapods: true
  directories:
    - node_modules
osx_image: xcode11
xcode_sdk: iphonesimulator11.0
podfile: $HOME/E2ETests/ios/Podfile

install:
  - yarn install
  - cd E2ETests && yarn install
  - yarn install:ios
  - brew install watchman
  - brew tap wix/brew
  - brew install wix/brew/applesimutils

script:
  - yarn build:ios
  - yarn test:ios

branches:
  only:
  - add-CI-tests
  # - master